#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gtk-frdp
Version  : 3.37.1
Release  : 1
URL      : https://gitlab.gnome.org/GNOME/gtk-frdp/-/archive/v3.37.1/gtk-frdp-v3.37.1.tar.gz
Source0  : https://gitlab.gnome.org/GNOME/gtk-frdp/-/archive/v3.37.1/gtk-frdp-v3.37.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: gtk-frdp-data = %{version}-%{release}
Requires: gtk-frdp-license = %{version}-%{release}
BuildRequires : FreeRDP-dev
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson

%description
No detailed description available

%package data
Summary: data components for the gtk-frdp package.
Group: Data

%description data
data components for the gtk-frdp package.


%package dev
Summary: dev components for the gtk-frdp package.
Group: Development
Requires: gtk-frdp-data = %{version}-%{release}
Provides: gtk-frdp-devel = %{version}-%{release}
Requires: gtk-frdp = %{version}-%{release}

%description dev
dev components for the gtk-frdp package.


%package license
Summary: license components for the gtk-frdp package.
Group: Default

%description license
license components for the gtk-frdp package.


%prep
%setup -q -n gtk-frdp-v3.37.1
cd %{_builddir}/gtk-frdp-v3.37.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1632330768
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gtk-frdp
cp %{_builddir}/gtk-frdp-v3.37.1/COPYING %{buildroot}/usr/share/package-licenses/gtk-frdp/a8a12e6867d7ee39c21d9b11a984066099b6fb6b
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GtkFrdp-0.1.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/gtk-frdp-0.1.deps
/usr/share/vala/vapi/gtk-frdp-0.1.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/gtk-frdp/frdp-display.h
/usr/include/gtk-frdp/frdp-session.h
/usr/include/gtk-frdp/gtk-frdp-version.h
/usr/include/gtk-frdp/gtk-frdp.h
/usr/lib64/libgtk-frdp-0.1.so
/usr/lib64/pkgconfig/gtk-frdp-0.1.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gtk-frdp/a8a12e6867d7ee39c21d9b11a984066099b6fb6b
