#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : gtk-frdp
Version  : 3.37.1
Release  : 11
URL      : https://gitlab.gnome.org/GNOME/gtk-frdp/-/archive/v3.37.1/gtk-frdp-v3.37.1.tar.gz
Source0  : https://gitlab.gnome.org/GNOME/gtk-frdp/-/archive/v3.37.1/gtk-frdp-v3.37.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: gtk-frdp-data = %{version}-%{release}
Requires: gtk-frdp-lib = %{version}-%{release}
Requires: gtk-frdp-license = %{version}-%{release}
BuildRequires : FreeRDP-dev
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : fuse-dev
BuildRequires : pkgconfig(fuse3)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: backport-8bf5267b85310a1c06463dc41ec5f388bec5f232.patch
Patch2: backport-acf9029de66bc1c49b0f4ce322bbfb57a5296de8.patch
Patch3: backport-6cd301dc5ee82b1e2c33ab3b9e2498c6f08320ef.patch
Patch4: backport-805721e82ca1df6a50da3b5bd3b75d6747016482.patch
Patch5: backport-a837c36e19260e9b8e9c7b5845ba1aca499c455b.patch
Patch6: backport-cda768ba53e82321954f4a3f973ca6c454e7bd5c.patch
Patch7: backport-7ce17bea7d77e745934a396cb309cf2fabdd1fa8.patch
Patch8: backport-d20600878d10ed50aa8025790347eee8c073e3d0.patch
Patch9: backport-8fed58a28edd36923d677a2eb4412919a24f5532.patch
Patch10: backport-6727ad9a21f1a428206f512f2988047d398fce8f.patch
Patch11: backport-5151ad3a4ba65d19a8b5d92c7fe785686a6ff9b2.patch
Patch12: backport-b5b82542df115270e49c29e12505412f6df28394.patch
Patch13: backport-02f130ef4a5963605a5de0aaa4b3ebb7b4aa4ee9.patch
Patch14: backport-6d3d5dd6f861e49a08d19a40dd47c9d9073a27d0.patch
Patch15: backport-4c29005344a0db2eb83b2cd987aab9774fa9c7c3.patch
Patch16: backport-b553d23d7a2e7e1cf735141557bf05e549c17496.patch
Patch17: backport-edea573d435ee13be393b4b263dfd9e40b82036f.patch
Patch18: backport-8564fdb768b81c212082de67a521230d10b8dc81.patch
Patch19: backport-bca7f1cd0c8dde4a4079041d81181e7e1a284966.patch
Patch20: backport-58bf0f5f642f5c198508dad1ad6e96148beabd64.patch
Patch21: backport-f5388fa93c48d9b7c48a307d6c18ed826db30c77.patch
Patch22: backport-02cfa78c26b184f6c31f450232976c28066c027b.patch
Patch23: backport-59971fb3fe27f434115eecbd74d03feed3c47fc7.patch
Patch24: backport-eb722de3f62853c0e5366d7d7cc9a037537dd263.patch
Patch25: backport-b92ab1a69396760800cd67d9e0b261823af5b6d9.patch
Patch26: backport-d5c491e2e14b703096079ad8e6d89e23452e46b8.patch
Patch27: backport-f96880327d1b343d4d46536f6cf7fd94a72dc054.patch
Patch28: backport-78f5fd2f7f888a01215444fe6d1c42c56b24a93a.patch
Patch29: backport-8e0e2a4c41e97c6d72e41b06822a4f0437824b6c.patch
Patch30: backport-a9b2bed03463601dd8c2cb7d8b6233624da33d8f.patch
Patch31: backport-c8498648c41349f64848438a2e7afb20a5a1e380.patch
Patch32: backport-e3ea9cf1dc137886f4e16c88f4f260eea323eda1.patch
Patch33: backport-5ab52648f8e85aa176b15acf3875d5b065caa3c4.patch
Patch34: backport-53f48ed156ea29d1df9c36e9fc9c5478ed59b2a7.patch
Patch35: backport-ab5e1081adcdfcb9ffb89bc3b016ae0a477bd86a.patch
Patch36: backport-700da76c062881b31b8002fb4c8964c3279b1ecd.patch
Patch37: backport-709e6c952c96c740135424e66fdf300f69ceb67a.patch
Patch38: backport-c4acfd496eb5545683db36815450ef5929b3f729.patch
Patch39: backport-d580998fdb93831cb65d1b1ce24cd691c703962b.patch
Patch40: backport-78dce5d8ff8523ca0f7b65a86ab4e6b317f6606a.patch
Patch41: backport-dbbff16cb127c501a2055b345de87a49639a9ca6.patch
Patch42: backport-bff676b318a3b561862248ad525c197b6f799c8c.patch
Patch43: backport-6a0483a04abb1a7215855c7447642d8e42219a8b.patch
Patch44: backport-f506b8a3e55a1bb4cab39c68c7c0c34629c78633.patch
Patch45: backport-1dcd08348078225ad0ff907dc0a565e8ac323d71.patch
Patch46: backport-4e7297e5b66a528a0e70a06136070d9b9bd700c3.patch
Patch47: backport-dcb0477d89fb84a4ff119a7f41bb97998b3db14d.patch
Patch48: backport-d94b0a0973662d0bbe33dd846f6b2dd0e09c5764.patch
Patch49: backport-ac20840808e2ed0c801755d9bc1b11f72e330006.patch
Patch50: backport-3f991a22c025cad3016a7aa55988e51884964050.patch
Patch51: backport-a7e2245c75c2fdf444b71cd8f6204248809f98d5.patch
Patch52: backport-9af99d95ed532128c1856e7a1bfd0b59dd61a35f.patch
Patch53: backport-3a4cc845aafccdc8a8db45f6a60c83b88d572788.patch
Patch54: backport-c6c03f2fafc56a92230e9a8eb9f611676a80e34e.patch
Patch55: backport-62fc62c5ccb7634f0bc87c57a4673877c24c94ed.patch
Patch56: backport-3d16c32d4b6deec5a46163fb34bdee9ed50c5fb5.patch
Patch57: backport-af7316a5b8baf9fc5b01bdd536be2c2cfc4cd2d0.patch
Patch58: backport-e9baa03fc46cc38180540a8356dcdc7743550b2d.patch
Patch59: backport-5e3571beb7ea7e4187719dbb09ddb4c6a5a02969.patch
Patch60: backport-403214fbdc8c4379393b49f0026771e6514d9c2f.patch
Patch61: backport-96e828c48fafcb4ede82f48d69be5280c58cdad0.patch
Patch62: backport-b29cd6eacf0bf4a05d3f10b2d00b09a04f26b1a5.patch
Patch63: backport-da0f1af4c117c8fadbe1d37a9e516fe3f2afcfed.patch
Patch64: backport-9086ab7e29c40865cf47f1bc4a391346c9fb9ba8.patch
Patch65: backport-11e9fcbee8ca5ec70456dd5b616b2560d7f73adc.patch
Patch66: backport-e3bdaf2c945c99151aa8db535f37a8786c388758.patch
Patch67: backport-59175a8e60c6344f2fff4369d6bff65a9abfa249.patch
Patch68: backport-97e166b7f2970ea5b723352fabac732cd6a0f41c.patch
Patch69: backport-433db195c8428643e37cd42281bddd2f9e2704c8.patch
Patch70: backport-cf10494813186ea2e4b3cad92821a74fbf0f6aaa.patch
Patch71: backport-9c1ff15c31e74b8fb0bee93d2bc57507bcf37e98.patch
Patch72: backport-95d0b96f326ad0253afff427541314b444babe29.patch
Patch73: backport-9eb05e575555a1ca2d2cff898d39f6d659e9bcda.patch
Patch74: backport-e050e4b069c0aab72d53378bcc7812a244f50d44.patch
Patch75: backport-42ec12a43596a2e799e2ae62b26fa28102d97259.patch
Patch76: backport-e97719d12ed9140dd33b9100596870ab9932b711.patch
Patch77: backport-e12603858cae178690c113d73b9d80991c6818da.patch
Patch78: backport-6cfdc840159bb349310c3b81cd2df949f1522760.patch
Patch79: backport-46ca0beb9b5bf8c9b245a596231016bcca9baf6b.patch

%description
No detailed description available

%package data
Summary: data components for the gtk-frdp package.
Group: Data

%description data
data components for the gtk-frdp package.


%package dev
Summary: dev components for the gtk-frdp package.
Group: Development
Requires: gtk-frdp-lib = %{version}-%{release}
Requires: gtk-frdp-data = %{version}-%{release}
Provides: gtk-frdp-devel = %{version}-%{release}
Requires: gtk-frdp = %{version}-%{release}

%description dev
dev components for the gtk-frdp package.


%package lib
Summary: lib components for the gtk-frdp package.
Group: Libraries
Requires: gtk-frdp-data = %{version}-%{release}
Requires: gtk-frdp-license = %{version}-%{release}

%description lib
lib components for the gtk-frdp package.


%package license
Summary: license components for the gtk-frdp package.
Group: Default

%description license
license components for the gtk-frdp package.


%prep
%setup -q -n gtk-frdp-v3.37.1
cd %{_builddir}/gtk-frdp-v3.37.1
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
%patch -P 5 -p1
%patch -P 6 -p1
%patch -P 7 -p1
%patch -P 8 -p1
%patch -P 9 -p1
%patch -P 10 -p1
%patch -P 11 -p1
%patch -P 12 -p1
%patch -P 13 -p1
%patch -P 14 -p1
%patch -P 15 -p1
%patch -P 16 -p1
%patch -P 17 -p1
%patch -P 18 -p1
%patch -P 19 -p1
%patch -P 20 -p1
%patch -P 21 -p1
%patch -P 22 -p1
%patch -P 23 -p1
%patch -P 24 -p1
%patch -P 25 -p1
%patch -P 26 -p1
%patch -P 27 -p1
%patch -P 28 -p1
%patch -P 29 -p1
%patch -P 30 -p1
%patch -P 31 -p1
%patch -P 32 -p1
%patch -P 33 -p1
%patch -P 34 -p1
%patch -P 35 -p1
%patch -P 36 -p1
%patch -P 37 -p1
%patch -P 38 -p1
%patch -P 39 -p1
%patch -P 40 -p1
%patch -P 41 -p1
%patch -P 42 -p1
%patch -P 43 -p1
%patch -P 44 -p1
%patch -P 45 -p1
%patch -P 46 -p1
%patch -P 47 -p1
%patch -P 48 -p1
%patch -P 49 -p1
%patch -P 50 -p1
%patch -P 51 -p1
%patch -P 52 -p1
%patch -P 53 -p1
%patch -P 54 -p1
%patch -P 55 -p1
%patch -P 56 -p1
%patch -P 57 -p1
%patch -P 58 -p1
%patch -P 59 -p1
%patch -P 60 -p1
%patch -P 61 -p1
%patch -P 62 -p1
%patch -P 63 -p1
%patch -P 64 -p1
%patch -P 65 -p1
%patch -P 66 -p1
%patch -P 67 -p1
%patch -P 68 -p1
%patch -P 69 -p1
%patch -P 70 -p1
%patch -P 71 -p1
%patch -P 72 -p1
%patch -P 73 -p1
%patch -P 74 -p1
%patch -P 75 -p1
%patch -P 76 -p1
%patch -P 77 -p1
%patch -P 78 -p1
%patch -P 79 -p1
pushd ..
cp -a gtk-frdp-v3.37.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738010770
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/gtk-frdp
cp %{_builddir}/gtk-frdp-v%{version}/COPYING %{buildroot}/usr/share/package-licenses/gtk-frdp/a8a12e6867d7ee39c21d9b11a984066099b6fb6b || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GtkFrdp-0.2.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/gtk-frdp-0.2.deps
/usr/share/vala/vapi/gtk-frdp-0.2.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/gtk-frdp/frdp-display.h
/usr/include/gtk-frdp/frdp-session.h
/usr/include/gtk-frdp/gtk-frdp-version.h
/usr/include/gtk-frdp/gtk-frdp.h
/usr/lib64/pkgconfig/gtk-frdp-0.2.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libgtk-frdp-0.2.so
/usr/lib64/libgtk-frdp-0.2.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gtk-frdp/a8a12e6867d7ee39c21d9b11a984066099b6fb6b
